# Generated by Django 4.0.3 on 2022-03-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='owner_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
