# Generated by Django 4.0.3 on 2022-03-22 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0002_bussiness_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness',
            name='NeighbourHood_Id',
        ),
        migrations.AddField(
            model_name='bussiness',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
